Solve 01-basics
js-tasks-ru/vue-20240924_skvor pull request #2
Opened 2024-09-27 19:35 UTC by Jenackler

Solve 01-basics/10-create-app
Solve 01-basics/20-weather

2024-09-27 19:35 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-01 19:32 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-10-01 19:33 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-10-04 16:43 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-10-06 16:19 UTC, ShGKme requested changes

2024-10-06 16:19 UTC, ShGKme commented on 01-basics/10-create-app/script.js
> +  template: 'Сегодня ' + new Date().toLocaleDateString(navigator.language, options),
Так определять шаблон некорректно. Здесь не инструментами Vue шаблоне описано, что должно выводиться, а сгенерирован сам шаблон на JS. Вместо этого шаблон должен быть фиксированной строкой, и уже внутри шаблона можно использовать директивы и текстовую интерполяцию для определения содержимого.

- Так собрать шаблон в основном формате Vue компонентов - SFC - вообще не возможно
- Значение шаблона определяется в момент описания компонента, а не в момент его работы. Так, если страница будет открыта сегодня, но компонент впервые срендерится только завтра - он всё равно выведет вчерашнюю дату

2024-10-06 16:19 UTC, ShGKme commented on 01-basics/10-create-app/script.js
> +  template: 'Сегодня ' + new Date().toLocaleDateString(navigator.language, options),
Если это было сделано, потому что `navigator.language` не доступен в шаблоне - лучше использовать переменную/функцию, описанную в `setup`.

2024-10-07 19:57 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-07 19:58 UTC, Jenackler commented
Исправлены указанные ошибки.
Добавлено решение для задач по компонентам

2024-10-07 19:59 UTC, Jenackler commented on 01-basics/10-create-app/script.js
> +  template: 'Сегодня ' + new Date().toLocaleDateString(navigator.language, options),
Загрузил исправления

2024-10-07 20:02 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-10-07 20:10 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-10-10 08:11 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-10-13 18:05 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-10-13 22:06 UTC, ShGKme approved these changes
Все задачи приняты

2024-10-13 22:09 UTC, merged

2024-10-13 22:09 UTC, ShGKme commented on 03-components/50-weather-components/components/weatherCard/WeatherCard.js
> +  },
Пропустил при проверке.

Сейчас для использования многих компонентов (включая компонент списка карточек) нужно передавать массив иконок. Это неудобно - пользователю даже списка, нужно иметь этот список, его кастомизации пока не требуется. Такая возможность может быть плюсом, если она дополнительная и опциональная (есть иконки по умолчанию). Но это неудобный интерфейс компонента, если для вывода списка нужно передавать объект иконок для разных погодных условий.

2024-10-13 22:09 UTC, ShGKme commented on 03-components/50-weather-components/WeatherApp.js
> +      <WeatherCardList :cardsList="wData" :icons="icons"/>
По стайл гайду принято пропсы (и события) в шаблоне использовать в `kebab-case`